class_name: Sequential
config:
- class_name: ZeroPadding2D
  config:
    batch_input_shape: !!python/tuple [null, 3, 64, 64]
    input_dtype: float32
    name: zeropadding2d_1
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_1
    nb_col: 3
    nb_filter: 64
    nb_row: 3
    subsample: &id001 !!python/tuple [1, 1]
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_2
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_2
    nb_col: 3
    nb_filter: 64
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: MaxPooling2D
  config:
    border_mode: valid
    dim_ordering: th
    name: maxpooling2d_1
    pool_size: !!python/tuple [2, 2]
    strides: !!python/tuple [2, 2]
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_3
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_3
    nb_col: 3
    nb_filter: 128
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_4
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_4
    nb_col: 3
    nb_filter: 128
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: MaxPooling2D
  config:
    border_mode: valid
    dim_ordering: th
    name: maxpooling2d_2
    pool_size: !!python/tuple [2, 2]
    strides: !!python/tuple [2, 2]
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_5
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_5
    nb_col: 3
    nb_filter: 256
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_6
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_6
    nb_col: 3
    nb_filter: 256
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_7
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_7
    nb_col: 3
    nb_filter: 256
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: MaxPooling2D
  config:
    border_mode: valid
    dim_ordering: th
    name: maxpooling2d_3
    pool_size: !!python/tuple [2, 2]
    strides: !!python/tuple [2, 2]
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_8
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_8
    nb_col: 3
    nb_filter: 512
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_9
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_9
    nb_col: 3
    nb_filter: 512
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_10
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: null
    activation: relu
    activity_regularizer: null
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_10
    nb_col: 3
    nb_filter: 512
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: MaxPooling2D
  config:
    border_mode: valid
    dim_ordering: th
    name: maxpooling2d_4
    pool_size: !!python/tuple [2, 2]
    strides: !!python/tuple [2, 2]
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_11
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: {l1: 1.0000000116860974e-07, l2: 1.0000000116860974e-07, name: WeightRegularizer}
    activation: relu
    activity_regularizer: {l1: 1.0000000116860974e-07, l2: 1.0000000116860974e-07,
      name: ActivityRegularizer}
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_11
    nb_col: 3
    nb_filter: 512
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_12
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: {l1: 9.999999974752427e-07, l2: 9.999999974752427e-07, name: WeightRegularizer}
    activation: relu
    activity_regularizer: {l1: 9.999999974752427e-07, l2: 9.999999974752427e-07, name: ActivityRegularizer}
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_12
    nb_col: 3
    nb_filter: 512
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: ZeroPadding2D
  config:
    name: zeropadding2d_13
    padding: !!python/tuple [1, 1]
    trainable: true
- class_name: Convolution2D
  config:
    W_constraint: null
    W_regularizer: {l1: 9.999999747378752e-06, l2: 9.999999747378752e-06, name: WeightRegularizer}
    activation: relu
    activity_regularizer: {l1: 9.999999747378752e-06, l2: 9.999999747378752e-06, name: ActivityRegularizer}
    b_constraint: null
    b_regularizer: null
    bias: true
    border_mode: valid
    dim_ordering: th
    init: glorot_uniform
    name: convolution2d_13
    nb_col: 3
    nb_filter: 512
    nb_row: 3
    subsample: *id001
    trainable: true
- class_name: MaxPooling2D
  config:
    border_mode: valid
    dim_ordering: th
    name: maxpooling2d_5
    pool_size: !!python/tuple [2, 2]
    strides: !!python/tuple [2, 2]
    trainable: true
- class_name: Flatten
  config: {name: flatten_1, trainable: true}
- class_name: Dense
  config:
    W_constraint: null
    W_regularizer: {l1: 9.999999747378752e-05, l2: 9.999999747378752e-05, name: WeightRegularizer}
    activation: relu
    activity_regularizer: {l1: 9.999999747378752e-06, l2: 9.999999747378752e-06, name: ActivityRegularizer}
    b_constraint: null
    b_regularizer: null
    bias: true
    init: glorot_uniform
    input_dim: null
    name: dense_1
    output_dim: 4096
    trainable: true
- class_name: Dropout
  config: {name: dropout_1, p: 0.75, trainable: true}
- class_name: Dense
  config:
    W_constraint: null
    W_regularizer: {l1: 9.999999747378752e-05, l2: 9.999999747378752e-05, name: WeightRegularizer}
    activation: relu
    activity_regularizer: {l1: 9.999999747378752e-06, l2: 9.999999747378752e-06, name: ActivityRegularizer}
    b_constraint: null
    b_regularizer: null
    bias: true
    init: glorot_uniform
    input_dim: null
    name: dense_2
    output_dim: 4096
    trainable: true
- class_name: Dropout
  config: {name: dropout_2, p: 0.75, trainable: true}
- class_name: Dense
  config: {W_constraint: null, W_regularizer: null, activation: linear, activity_regularizer: null,
    b_constraint: null, b_regularizer: null, bias: true, init: glorot_uniform, input_dim: null,
    name: dense_3, output_dim: 201, trainable: true}
- class_name: Activation
  config: {activation: softmax, name: activation_1, trainable: true}
keras_version: 1.0.6
loss: categorical_crossentropy
optimizer: {beta_1: 0.8999999761581421, beta_2: 0.9990000128746033, epsilon: 1.0e-08,
  lr: 0.0020000000949949026, name: Nadam, schedule_decay: 0.004}
sample_weight_mode: null
